@host = http://127.0.0.1
@port = 8000


###🔍 GET /usuarios/id // para probarla primerohay que loguearse y obtener el token 

GET {{host}}:{{port}}/usuarios/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJsYXVyYUBkZW1vLmNvbSIsIm5vbWJyZSI6IkxhdXJhIiwicm9sIjoiY2xpZW50ZSIsImV4cCI6MTc3MDUzNTUyMX0.Er1xCu9HD8-R25OTYw_w0C3b7J8XqBSzSkhcWiEbVF4


### (prueba con otro id)
GET {{host}}:{{port}}/usuarios/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJsYXVyYUBkZW1vLmNvbSIsIm5vbWJyZSI6IkxhdXJhIiwicm9sIjoiY2xpZW50ZSIsImV4cCI6MTc3MDUzNTUyMX0.Er1xCu9HD8-R25OTYw_w0C3b7J8XqBSzSkhcWiEbVF4


### cambio password 
PUT {{host}}:{{port}}/usuarios/13/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoibGF1Lm1vbnRpcm9uaUBnbWFpbC5jb20iLCJub21icmUiOiJMYXVyYU9LICIsInJvbCI6ImNsaWVudGUiLCJleHAiOjE3NzExNjc3MTZ9.UaesDSu--60sZe_vDDcepwKcZVqx-x6sOIvyr8zsIVg
Content-Type: application/json

{
  "current_password": "Deemo1234",
  "new_password": "Demo1234"
}